Documentation Update
MMercer8989/OpenTournament pull request #14
Opened 2021-04-17 22:12 UTC by mryindles

Rolled out big changes to our user stories document to reflect the drastic change in direction the project has taken. Created readme.md as per project instructions, and moved original open tournament developer readme to our documentation folder. Only making this a pull request because this needs to get rolled out to master, and master is a protected branch. Please view all documentation changes, and let me know you approve of them.

2021-04-17 22:22 UTC, MMercer8989 approved these changes
For the most part, everything looks and reads adequately, though I would suggest capitalizing The header for the test coverage section and the project info section to match the formatting for the rest of the document.

2021-04-17 22:31 UTC, MMercer8989 commented
Additionally, the updates to the user stories document seem alright. I might suggest taking out the word incentivizing for C4P-44, and changing instances of "Matthew" to "Matt"(my full name is Matt) to avoid any confusion when grading. other than those two nitpicks though, I would say it's good to go.

2021-04-17 23:58 UTC, daniellcurto requested changes
I do agree we did not realize what we were doing wrong until the professor said something. At least we realized it now and not after Dr. Buck graded our project. So far,  I am not sure what else to say about this commit.

2021-04-18 00:22 UTC, daniellcurto approved these changes

2021-04-18 00:23 UTC, merged